packages:
  - "apps/*"
  - "packages/*"
  - "workers/*"

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "esbuild"
  - "prisma"
  - "sharp"
  - "unrs-resolver"
  - "workerd"

overrides:
  react: "19.2.8"
  react-dom: "19.2.8"
