packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  esbuild: false
  prisma: set this to true or false
  sharp: false
  unrs-resolver: false
  workerd: false
