import { PurchaseRequest } from "@/types/procurement";

export const INITIAL_PURCHASE_REQUESTS: PurchaseRequest[] = [
  {
    id: "req-1",
    referenceNumber: "PR-2026-001",
    title: "Structural Ready-Mix Concrete (Grade C35/45) - Foundation Pour",
    description:
      "Supply and on-site transit mixer delivery of Grade C35/45 sulphate-resisting ready-mix concrete for Phase 2 Substructure & Foundation casting at Riyadh Metro Station Package 4.",
    department: "Civil & Structural Engineering",
    requesterName: "Tariq Al-Ghamdi (Site Engineer)",
    priority: "high",
    requiredByDate: "2026-09-15",
    status: "submitted",
    currency: "SAR",
    items: [
      {
        id: "item-1-1",
        name: "Ready-Mix Concrete Grade C35/45 (SRC - Sulphate Resisting)",
        category: "Concrete & Masonry",
        quantity: 450,
        unit: "m³",
        estimatedUnitPrice: 260,
        totalPrice: 117000,
        preferredVendor: "Saudi ReadyMix Co.",
        notes: "Includes slump test certification and temperature control",
      },
      {
        id: "item-1-2",
        name: "Stationary Concrete Boom Pump (36m Reach)",
        category: "Heavy Plant & Equipment",
        quantity: 2,
        unit: "shifts",
        estimatedUnitPrice: 4500,
        totalPrice: 9000,
        preferredVendor: "Al-Kifah Equipment Rental",
        notes: "Includes certified operator and pump line setup",
      },
    ],
    totalEstimatedAmount: 126000,
    attachments: [
      {
        id: "att-1",
        name: "Concrete_Mix_Design_Approval_Rev3.pdf",
        size: 1840000,
        type: "application/pdf",
        url: "#",
        uploadedAt: "2026-08-25T09:12:00Z",
      },
      {
        id: "att-2",
        name: "Foundation_Pour_Schedule_Phase2.pdf",
        size: 920000,
        type: "application/pdf",
        url: "#",
        uploadedAt: "2026-08-25T09:15:00Z",
      },
    ],
    createdAt: "2026-08-25T09:16:00Z",
    updatedAt: "2026-08-25T09:16:00Z",
    auditTrail: [
      {
        id: "log-1-1",
        action: "Requisition Submitted",
        actorName: "Tariq Al-Ghamdi",
        actorRole: "requester",
        timestamp: "2026-08-25T09:16:00Z",
        note: "Submitted new requisition request for admin review.",
        previousStatus: "draft",
        newStatus: "submitted",
      },
    ],
  },
  {
    id: "req-2",
    referenceNumber: "PR-2026-002",
    title: "High-Yield Deformed Steel Rebar (Grade 60 / ASTM A615)",
    description:
      "Procurement of 16mm and 25mm high-strength ribbed steel reinforcement bars (cut & bend schedules included) for Riyadh Metro Station retaining walls and column reinforcement.",
    department: "Civil & Structural Engineering",
    requesterName: "Fahad Al-Otaibi (Project Procurement Lead)",
    priority: "urgent",
    requiredByDate: "2026-09-05",
    status: "under_review",
    currency: "SAR",
    items: [
      {
        id: "item-2-1",
        name: "Deformed Steel Rebar 16mm (Grade 60, 12m lengths)",
        category: "Steel & Metals",
        quantity: 85,
        unit: "Tons",
        estimatedUnitPrice: 2850,
        totalPrice: 242250,
        preferredVendor: "SABIC / Hadeed Steel",
        notes: "Mill test certificates and SASO compliance required with delivery",
      },
      {
        id: "item-2-2",
        name: "Deformed Steel Rebar 25mm (Grade 60, 12m lengths)",
        category: "Steel & Metals",
        quantity: 120,
        unit: "Tons",
        estimatedUnitPrice: 2820,
        totalPrice: 338400,
        preferredVendor: "Al-Yamamah Steel Industries",
        notes: "Factory bundled, anti-rust treated for transit",
      },
    ],
    totalEstimatedAmount: 580650,
    attachments: [
      {
        id: "att-3",
        name: "Bar_Bending_Schedule_BBS_Rev4.pdf",
        size: 3400000,
        type: "application/pdf",
        url: "#",
        uploadedAt: "2026-08-26T11:00:00Z",
      },
      {
        id: "att-4",
        name: "SASO_Steel_Compliance_Spec.pdf",
        size: 1100000,
        type: "application/pdf",
        url: "#",
        uploadedAt: "2026-08-26T11:05:00Z",
      },
    ],
    createdAt: "2026-08-26T11:10:00Z",
    updatedAt: "2026-08-27T08:30:00Z",
    auditTrail: [
      {
        id: "log-2-1",
        action: "Requisition Submitted",
        actorName: "Fahad Al-Otaibi",
        actorRole: "requester",
        timestamp: "2026-08-26T11:10:00Z",
        previousStatus: "draft",
        newStatus: "submitted",
      },
      {
        id: "log-2-2",
        action: "Assigned & Status Changed",
        actorName: "Procurement Committee",
        actorRole: "admin",
        timestamp: "2026-08-27T08:30:00Z",
        note: "Moved to technical & commercial review. Requesting mill certificates.",
        previousStatus: "submitted",
        newStatus: "under_review",
      },
    ],
  },
  {
    id: "req-3",
    referenceNumber: "PR-2026-003",
    title: "Heavy Mobile Crawler Crane (120-Ton Capacity) - 30-Day Site Rental",
    description:
      "Monthly dry lease of 120-Ton telescopic boom crawler crane for precast beam erection and heavy girder positioning over trackway span.",
    department: "Heavy Plant & Equipment",
    requesterName: "Eng. Bilal Mansoor (Heavy Lift Supervisor)",
    priority: "medium",
    requiredByDate: "2026-09-20",
    status: "approved",
    currency: "SAR",
    items: [
      {
        id: "item-3-1",
        name: "120-Ton Crawler Crane (Liebherr LR 1130 or equivalent)",
        category: "Heavy Plant & Equipment",
        quantity: 1,
        unit: "months",
        estimatedUnitPrice: 85000,
        totalPrice: 85000,
        preferredVendor: "Kanoo Machinery / Heavy Equipment Co.",
        notes: "Valid 3rd party Aramco/TUV inspection certificate compulsory",
      },
    ],
    totalEstimatedAmount: 85000,
    attachments: [
      {
        id: "att-5",
        name: "TUV_Crane_Inspection_Checklist.pdf",
        size: 540000,
        type: "application/pdf",
        url: "#",
        uploadedAt: "2026-08-24T14:20:00Z",
      },
    ],
    createdAt: "2026-08-24T14:25:00Z",
    updatedAt: "2026-08-26T16:00:00Z",
    auditTrail: [
      {
        id: "log-3-1",
        action: "Requisition Submitted",
        actorName: "Eng. Bilal Mansoor",
        actorRole: "requester",
        timestamp: "2026-08-24T14:25:00Z",
        newStatus: "submitted",
      },
      {
        id: "log-3-2",
        action: "Approved for Sourcing",
        actorName: "VP of Project Execution",
        actorRole: "admin",
        timestamp: "2026-08-26T16:00:00Z",
        note: "Approved. Issue RFQ to Kanoo Machinery and Zahid Tractor.",
        previousStatus: "under_review",
        newStatus: "approved",
      },
    ],
  },
  {
    id: "req-4",
    referenceNumber: "PR-2026-004",
    title: "MEP Electrical Substation Switchgear & Cable Trays",
    description:
      "Procurement of 13.8kV Medium Voltage Switchgear panels, 600mm heavy-duty perforated galvanized cable trays, and earthing busbars for traction substation room.",
    department: "MEP & Electrical",
    requesterName: "Kareem Nassar (Lead Electrical Engineer)",
    priority: "high",
    requiredByDate: "2026-10-01",
    status: "submitted",
    currency: "SAR",
    items: [
      {
        id: "item-4-1",
        name: "13.8kV Gas-Insulated Switchgear (GIS) Panel (4-Breaker Setup)",
        category: "Electrical & Instrumentation",
        quantity: 2,
        unit: "sets",
        estimatedUnitPrice: 175000,
        totalPrice: 350000,
        preferredVendor: "Schneider Electric Saudi / ABB",
        notes: "Factory acceptance test (FAT) reports required prior to shipping",
      },
      {
        id: "item-4-2",
        name: "Hot-Dip Galvanized Cable Tray 600mm x 100mm (3m lengths)",
        category: "Electrical & Instrumentation",
        quantity: 400,
        unit: "meters",
        estimatedUnitPrice: 145,
        totalPrice: 58000,
        preferredVendor: "Saudi Cable Company",
        notes: "Includes couplers, splice plates, and stainless fasteners",
      },
    ],
    totalEstimatedAmount: 408000,
    attachments: [
      {
        id: "att-6",
        name: "Single_Line_Diagram_SLD_Traction_Substation.pdf",
        size: 4200000,
        type: "application/pdf",
        url: "#",
        uploadedAt: "2026-08-27T10:15:00Z",
      },
    ],
    createdAt: "2026-08-27T10:20:00Z",
    updatedAt: "2026-08-27T10:20:00Z",
    auditTrail: [
      {
        id: "log-4-1",
        action: "Requisition Submitted",
        actorName: "Kareem Nassar",
        actorRole: "requester",
        timestamp: "2026-08-27T10:20:00Z",
        newStatus: "submitted",
      },
    ],
  },
  {
    id: "req-5",
    referenceNumber: "PR-2026-005",
    title: "High-Volume Diesel Fuel (Ultra-Low Sulfur) - Generator & Fleet Supply",
    description:
      "Monthly scheduled on-site fuel tanker delivery (50,000 Liters) for station tower cranes, continuous running 500kVA backup diesel generators, and heavy earthmoving machinery.",
    department: "Plant Logistics & Site Facilities",
    requesterName: "Salem Al-Harthi (Site Logistics Manager)",
    priority: "medium",
    requiredByDate: "2026-09-01",
    status: "approved",
    currency: "SAR",
    items: [
      {
        id: "item-5-1",
        name: "Ultra-Low Sulfur Diesel Fuel (Aramco Standard 10ppm)",
        category: "Consumables & Fuel",
        quantity: 50000,
        unit: "Liters",
        estimatedUnitPrice: 1.15,
        totalPrice: 57500,
        preferredVendor: "Saudi Aramco Retail / Aldrees Petroleum",
        notes: "Direct on-site tanker discharge to primary 60,000L fuel storage farm",
      },
    ],
    totalEstimatedAmount: 57500,
    attachments: [
      {
        id: "att-7",
        name: "Fuel_Consumption_Projection_Q3.xlsx",
        size: 180000,
        type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        url: "#",
        uploadedAt: "2026-08-23T15:00:00Z",
      },
    ],
    createdAt: "2026-08-23T15:05:00Z",
    updatedAt: "2026-08-24T09:00:00Z",
    auditTrail: [
      {
        id: "log-5-1",
        action: "Requisition Submitted",
        actorName: "Salem Al-Harthi",
        actorRole: "requester",
        timestamp: "2026-08-23T15:05:00Z",
        newStatus: "submitted",
      },
      {
        id: "log-5-2",
        action: "Approved",
        actorName: "Finance & Operations Director",
        actorRole: "admin",
        timestamp: "2026-08-24T09:00:00Z",
        note: "Auto-approved monthly operational consumables.",
        previousStatus: "submitted",
        newStatus: "approved",
      },
    ],
  },
  {
    id: "req-6",
    referenceNumber: "PR-2026-006",
    title: "Personal Protective Equipment (PPE) - Site Wide Bulk Replenishment",
    description:
      "Annual replenishment of safety equipment including EN397 safety helmets, EN20471 Class 3 reflective vests, S3 steel-toe safety boots, cut-resistant gloves, and safety goggles for 350 active site operatives.",
    department: "Health, Safety & Environment (HSE)",
    requesterName: "Nasser Al-Subaie (Head of Site HSE)",
    priority: "low",
    requiredByDate: "2026-09-30",
    status: "draft",
    currency: "SAR",
    items: [
      {
        id: "item-6-1",
        name: "Industrial Safety Helmets (EN 397 with chin strap)",
        category: "Safety & PPE",
        quantity: 400,
        unit: "pcs",
        estimatedUnitPrice: 45,
        totalPrice: 18000,
        preferredVendor: "Delta Plus / 3M Safety Arabia",
      },
      {
        id: "item-6-2",
        name: "S3 Composite Toe Leather Safety Boots (Various Sizes 40-46)",
        category: "Safety & PPE",
        quantity: 350,
        unit: "pairs",
        estimatedUnitPrice: 160,
        totalPrice: 56000,
        preferredVendor: "Red Wing Saudi Arabia",
      },
      {
        id: "item-6-3",
        name: "High-Visibility Safety Vests (ANSI/ISEA 107 Class 3)",
        category: "Safety & PPE",
        quantity: 600,
        unit: "pcs",
        estimatedUnitPrice: 25,
        totalPrice: 15000,
        preferredVendor: "Al-Gabbani Safety Equipment",
      },
    ],
    totalEstimatedAmount: 89000,
    attachments: [],
    createdAt: "2026-08-27T16:00:00Z",
    updatedAt: "2026-08-27T16:00:00Z",
    auditTrail: [
      {
        id: "log-6-1",
        action: "Draft Created",
        actorName: "Nasser Al-Subaie",
        actorRole: "requester",
        timestamp: "2026-08-27T16:00:00Z",
        newStatus: "draft",
      },
    ],
  },
];
