import { FaFacebook, FaHardHat } from "react-icons/fa";
import {
  FiArrowRight,
  FiCheckCircle,
  FiChevronDown,
  FiChevronRight,
  FiClock,
  FiFile,
  FiImage,
  FiInstagram,
  FiLinkedin,
  FiLock,
  FiMail,
  FiMapPin,
  FiMenu,
  FiMoon,
  FiPhone,
  FiPlus,
  FiSearch,
  FiShield,
  FiSun,
  FiX,
} from "react-icons/fi";

export const Icons = {
  Menu: FiMenu,
  Close: FiX,
  Linkedin: FiLinkedin,
  Instagram: FiInstagram,
  Facebook: FaFacebook,
  Moon: FiMoon,
  Sun: FiSun,
  ArrowRight: FiArrowRight,
  ChevronRight: FiChevronRight,
  ChevronDown: FiChevronDown,
  MapPin: FiMapPin,
  Phone: FiPhone,
  Mail: FiMail,
  Clock: FiClock,
  Check: FiCheckCircle,
  Construction: FaHardHat,
  Plus: FiPlus,
  Gallery: FiImage,
  Search: FiSearch,
  File: FiFile,
  Shield: FiShield,
  Lock: FiLock,
};

export type IconType = keyof typeof Icons;
