import { FaFacebook, FaHardHat, FaPalette } from "react-icons/fa";
import {
  FiArrowRight,
  FiCheckCircle,
  FiChevronDown,
  FiChevronLeft,
  FiChevronRight,
  FiChevronsLeft,
  FiChevronsRight,
  FiClock,
  FiDownload,
  FiEye,
  FiFile,
  FiImage,
  FiInstagram,
  FiLayout,
  FiLinkedin,
  FiList,
  FiLock,
  FiMail,
  FiMapPin,
  FiMaximize,
  FiMenu,
  FiMinimize,
  FiMinus,
  FiMoon,
  FiMoreHorizontal,
  FiPause,
  FiPhone,
  FiPlay,
  FiPlus,
  FiSearch,
  FiShare2,
  FiShield,
  FiSun,
  FiX,
} from "react-icons/fi";

export const Icons = {
  Menu: FiMenu,
  Close: FiX,
  Linkedin: FiLinkedin,
  Instagram: FiInstagram,
  Facebook: FaFacebook,
  Moon: FiMoon,
  Sun: FiSun,
  ArrowRight: FiArrowRight,
  ChevronLeft: FiChevronLeft,
  ChevronRight: FiChevronRight,
  ChevronDown: FiChevronDown,
  ChevronsLeft: FiChevronsLeft,
  ChevronsRight: FiChevronsRight,
  MapPin: FiMapPin,
  Phone: FiPhone,
  Mail: FiMail,
  Clock: FiClock,
  Check: FiCheckCircle,
  Construction: FaHardHat,
  Plus: FiPlus,
  Gallery: FiImage,
  Search: FiSearch,
  File: FiFile,
  Shield: FiShield,
  Lock: FiLock,
  Download: FiDownload,
  View: FiEye,
  Share: FiShare2,
  Minus: FiMinus,
  LayoutGrid: FiLayout,
  List: FiList,
  Play: FiPlay,
  Pause: FiPause,
  MoreHorizontal: FiMoreHorizontal,
  Maximize: FiMaximize,
  Minimize: FiMinimize,
  Palette: FaPalette,
};

export type IconType = keyof typeof Icons;
