import { PurchaseRequest } from "@/types/procurement";

export const INITIAL_PURCHASE_REQUESTS: PurchaseRequest[] = [
  {
    id: "req-1",
    referenceNumber: "PR-2026-001",
    title: "Structural Ready-Mix Concrete (Grade C35/45) - Foundation Pour",
    description:
      "Supply and on-site transit mixer delivery of Grade C35/45 sulphate-resisting ready-mix concrete for Phase 2 Substructure & Foundation casting at Riyadh Metro Station Package 4.",
    department: "Civil & Structural Engineering",
    requesterName: "Tariq Al-Ghamdi (Site Engineer)",
    priority: "high",
    requiredByDate: "2026-09-15",
    status: "submitted",
    currency: "SAR",
    items: [
      {
        id: "item-1-1",
        name: "Ready-Mix Concrete Grade C35/45 (SRC - Sulphate Resisting)",
        category: "Concrete & Masonry",
        quantity: 450,
        unit: "m³",
        estimatedUnitPrice: 260,
        totalPrice: 117000,
        preferredVendor: "Saudi ReadyMix Co.",
        notes: "Includes slump test certification and temperature control",
      },
      {
        id: "item-1-2",
        name: "Stationary Concrete Boom Pump (36m Reach)",
        category: "Heavy Plant & Equipment",
        quantity: 2,
        unit: "shifts",
        estimatedUnitPrice: 4500,
        totalPrice: 9000,
        preferredVendor: "Al-Kifah Equipment Rental",
        notes: "Includes certified operator and pump line setup",
      },
    ],
    totalEstimatedAmount: 126000,
    attachments: [
      {
        id: "att-1",
        name: "Concrete_Mix_Design_Approval_Rev3.pdf",
        size: 1840000,
        type: "application/pdf",
        url: "#",
        uploadedAt: "2026-08-25T09:12:00Z",
      },
      {
        id: "att-2",
        name: "Foundation_Pour_Schedule_Phase2.pdf",
        size: 920000,
        type: "application/pdf",
        url: "#",
        uploadedAt: "2026-08-25T09:15:00Z",
      },
    ],
    createdAt: "2026-08-25T09:16:00Z",
    updatedAt: "2026-08-25T09:16:00Z",
    auditTrail: [
      {
        id: "log-1-1",
        action: "Requisition Submitted",
        actorName: "Tariq Al-Ghamdi",
        actorRole: "requester",
        timestamp: "2026-08-25T09:16:00Z",
        note: "Submitted requisition with structural engineer mix design approval attached.",
        previousStatus: "draft",
        newStatus: "submitted",
      },
    ],
  },
  {
    id: "req-2",
    referenceNumber: "PR-2026-002",
    title: "High-Tensile Deformed Steel Rebar (Grade 60) - Columns & Beams",
    description:
      "Urgent procurement of ASTM A615 Grade 60 deformed rebar (16mm, 20mm, 25mm, and 32mm bundles) for superstructure frame reinforcement casting on Tower B.",
    department: "Civil & Structural Engineering",
    requesterName: "Sultan Mansour (Procurement Coordinator)",
    priority: "urgent",
    requiredByDate: "2026-08-30",
    status: "under_review",
    currency: "SAR",
    items: [
      {
        id: "item-2-1",
        name: "Deformed Steel Rebar 25mm (ASTM A615 Gr. 60 - 12m Bars)",
        category: "Steel & Metalwork",
        quantity: 85,
        unit: "tons",
        estimatedUnitPrice: 2850,
        totalPrice: 242250,
        preferredVendor: "SABIC Hadeed Steel",
        notes: "Mill test certificates required prior to delivery",
      },
      {
        id: "item-2-2",
        name: "Deformed Steel Rebar 16mm (ASTM A615 Gr. 60 - 12m Bars)",
        category: "Steel & Metalwork",
        quantity: 40,
        unit: "tons",
        estimatedUnitPrice: 2900,
        totalPrice: 116000,
        preferredVendor: "SABIC Hadeed Steel",
        notes: "Standard bundle packaging with weather-proof tags",
      },
      {
        id: "item-2-3",
        name: "Black Annealed Tie Wire (16 Gauge - 25kg Spools)",
        category: "Site Consumables",
        quantity: 50,
        unit: "boxes",
        estimatedUnitPrice: 140,
        totalPrice: 7000,
        preferredVendor: "Al-Muhaidib Building Materials",
      },
    ],
    totalEstimatedAmount: 365250,
    attachments: [
      {
        id: "att-3",
        name: "Bar_Bending_Schedule_BBS_TowerB.pdf",
        size: 3400000,
        type: "application/pdf",
        url: "#",
        uploadedAt: "2026-08-24T14:20:00Z",
      },
      {
        id: "att-4",
        name: "SABIC_Commercial_Quotation_Steel.pdf",
        size: 1100000,
        type: "application/pdf",
        url: "#",
        uploadedAt: "2026-08-24T14:35:00Z",
      },
    ],
    adminNotes: "Reviewing delivery logistics with central warehouse and site access manager.",
    createdAt: "2026-08-24T14:30:00Z",
    updatedAt: "2026-08-25T11:00:00Z",
    auditTrail: [
      {
        id: "log-2-1",
        action: "Requisition Submitted",
        actorName: "Sultan Mansour",
        actorRole: "requester",
        timestamp: "2026-08-24T14:30:00Z",
        note: "Submitted with approved Bar Bending Schedule (BBS).",
        previousStatus: "draft",
        newStatus: "submitted",
      },
      {
        id: "log-2-2",
        action: "Under Admin Review",
        actorName: "RVCC Procurement Desk",
        actorRole: "admin",
        timestamp: "2026-08-25T11:00:00Z",
        note: "Rebar batch assigned to commercial evaluation team.",
        previousStatus: "submitted",
        newStatus: "under_review",
      },
    ],
  },
  {
    id: "req-3",
    referenceNumber: "PR-2026-003",
    title: "Heavy Equipment Rental: 50-Ton Mobile Rough Terrain Crane",
    description:
      "Monthly lease of 50-ton Tadano rough terrain mobile crane for heavy precast facade panel installation and structural steel truss erection on Site Sector 3.",
    department: "Heavy Plant & Machinery",
    requesterName: "Fahad Al-Otaibi (Plant Manager)",
    priority: "medium",
    requiredByDate: "2026-09-30",
    status: "approved",
    currency: "SAR",
    items: [
      {
        id: "item-3-1",
        name: "50-Ton Rough Terrain Mobile Crane (Tadano GR-500EX)",
        category: "Heavy Plant & Equipment",
        quantity: 1,
        unit: "months",
        estimatedUnitPrice: 38000,
        totalPrice: 38000,
        preferredVendor: "Kanoo Machinery Rental",
        notes: "Aramco-certified operator and valid third-party inspection sticker mandatory",
      },
      {
        id: "item-3-2",
        name: "Crane Rigging & Webbing Sling Set (10T Rated)",
        category: "Safety & Lifting Gear",
        quantity: 4,
        unit: "sets",
        estimatedUnitPrice: 1850,
        totalPrice: 7400,
        preferredVendor: "Gulf Lifting Supplies",
      },
    ],
    totalEstimatedAmount: 45400,
    attachments: [
      {
        id: "att-5",
        name: "Crane_Lifting_Plan_Method_Statement.pdf",
        size: 4200000,
        type: "application/pdf",
        url: "#",
        uploadedAt: "2026-08-20T10:00:00Z",
      },
      {
        id: "att-6",
        name: "Operator_Certifications_Aramco_Approved.pdf",
        size: 1500000,
        type: "application/pdf",
        url: "#",
        uploadedAt: "2026-08-20T10:05:00Z",
      },
    ],
    adminNotes: "Approved by Head of Plant Operations. PO issuance in progress.",
    createdAt: "2026-08-20T10:10:00Z",
    updatedAt: "2026-08-22T16:00:00Z",
    auditTrail: [
      {
        id: "log-3-1",
        action: "Requisition Submitted",
        actorName: "Fahad Al-Otaibi",
        actorRole: "requester",
        timestamp: "2026-08-20T10:10:00Z",
        note: "Submitted with lifting plan risk assessment.",
        previousStatus: "draft",
        newStatus: "submitted",
      },
      {
        id: "log-3-2",
        action: "Requisition Approved",
        actorName: "Procurement Committee",
        actorRole: "admin",
        timestamp: "2026-08-22T16:00:00Z",
        note: "Commercial terms verified with Kanoo Machinery. Approved for dispatch.",
        previousStatus: "submitted",
        newStatus: "approved",
      },
    ],
  },
  {
    id: "req-4",
    referenceNumber: "PR-2026-004",
    title: "MEP Electrical Substation Cabling & Fire-Rated Cable Trays",
    description:
      "Procurement of low-smoke zero-halogen (LSZH) XLPE copper power cables (4x240mm²) and hot-dip galvanized cable trays for basement central substation electrical rough-in.",
    department: "MEP & Electrical Systems",
    requesterName: "Eng. Bilal Qasim",
    priority: "medium",
    requiredByDate: "2026-10-05",
    status: "submitted",
    currency: "SAR",
    items: [
      {
        id: "item-4-1",
        name: "XLPE/LSZH Copper Power Cable (0.6/1kV 4x240mm² Cu/XLPE/LSZH)",
        category: "MEP & Electrical",
        quantity: 650,
        unit: "meters",
        estimatedUnitPrice: 210,
        totalPrice: 136500,
        preferredVendor: "Saudi Cable Company",
        notes: "Fire performance standard BS 6724 certified",
      },
      {
        id: "item-4-2",
        name: "Perforated HDG Heavy Duty Cable Tray (600mm x 50mm x 3m)",
        category: "MEP & Electrical",
        quantity: 120,
        unit: "pcs",
        estimatedUnitPrice: 145,
        totalPrice: 17400,
        preferredVendor: "Riyadh Cable Trays Co.",
      },
    ],
    totalEstimatedAmount: 153900,
    attachments: [
      {
        id: "att-7",
        name: "MEP_Substation_Single_Line_Diagram_SLD.pdf",
        size: 2750000,
        type: "application/pdf",
        url: "#",
        uploadedAt: "2026-08-26T11:00:00Z",
      },
    ],
    createdAt: "2026-08-26T11:15:00Z",
    updatedAt: "2026-08-26T11:15:00Z",
    auditTrail: [
      {
        id: "log-4-1",
        action: "Requisition Submitted",
        actorName: "Eng. Bilal Qasim",
        actorRole: "requester",
        timestamp: "2026-08-26T11:15:00Z",
        note: "Submitted with electrical load schedule and single-line diagram.",
        previousStatus: "draft",
        newStatus: "submitted",
      },
    ],
  },
];
