import {
  LuArrowRight as ArrowRight,
  LuChevronDown as ChevronDown,
  LuChevronLeft as ChevronLeft,
  LuChevronRight as ChevronRight,
  LuFile as File,
  LuLayoutGrid as LayoutGrid,
  LuMapPin as MapPin,
  LuMaximize as Maximize,
  LuMinimize as Minimize,
  LuMinus as Minus,
  LuMoon as Moon,
  LuPause as Pause,
  LuPlay as Play,
  LuPlus as Plus,
  LuSearch as Search,
  LuShare2 as Share2,
  LuShield as Shield,
  LuSun as Sun,
  LuX as X,
  LuPalette as Palette,
} from "react-icons/lu";
import { FaFacebookF, FaInstagram, FaLinkedinIn } from "react-icons/fa6";

/** Lucide / react-icons under the legacy `Icons.*` names. */
export const Icons = {
  ArrowRight,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Close: X,
  Facebook: FaFacebookF,
  File,
  Instagram: FaInstagram,
  LayoutGrid,
  Linkedin: FaLinkedinIn,
  MapPin,
  Maximize,
  Minimize,
  Minus,
  Moon,
  Pause,
  Play,
  Plus,
  Search,
  Share: Share2,
  Shield,
  Sun,
  Palette,
};
